<a href="https://colab.research.google.com/github/harinisri18/harinisri18/blob/main/DEEP_LEARNING_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LAB ASSIGNMENT 1

DEEP LEARNING

NAME : G.HARINISRI

REG NO: 19MIA1069

QUESTION : CONSTRUCTION OF NEURAL NETWORK USING KERAS MODEL

In [2]:
#IMPORTING REQUIRED PACKAGES
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
#IMPORTING KERAS MODEL PACKAGES
import keras
from keras.models import Sequential
from keras.layers import Dense, Activation
from  tensorflow.keras.optimizers import SGD

from sklearn.metrics import classification_report, confusion_matrix

In [5]:
df = pd.read_csv("/content/drive/MyDrive/iris.data.txt")

In [6]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [7]:
#PERFORMING DATA ANALYSIS

In [8]:
df.shape

(150, 5)

In [9]:
df.describe()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     150.000000    150.000000     150.000000    150.000000
mean        5.843333      3.054000       3.758667      1.198667
std         0.828066      0.433594       1.764420      0.763161
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.350000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [11]:
df.isnull().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [12]:
x = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = df['Species']
df1 = x

In [13]:
#TRANSFORMING THE DATASET 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [14]:
data_x = scaler.fit_transform(x.values)
df2 = pd.DataFrame(data_x, index = x.index, columns = x.columns)

In [15]:
#SPLITTING THE DATASET
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df2.values, y, test_size = 0.2, random_state=42)

In [16]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.fit_transform(y_test)

In [20]:
from keras.utils import np_utils
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train, num_classes = 3)
y_test = to_categorical(y_test, num_classes = 3)


In [21]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120, 3)
(30, 3)


In [22]:
model = Sequential()
model.add(Dense(100, activation='relu', input_dim=4))
model.add(Dense(3, activation='softmax'))
sgd = SGD(lr = 0.01, decay = 1e-6, momentum = 0.9, nesterov=True)
model.compile(optimizer=sgd,
              loss='categorical_crossentropy',
              metrics=['accuracy'])

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/gradient_descent.py:102: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


In [23]:
history = model.fit(X_train, y_train, epochs = 300, batch_size = 32)

Epoch 1/300
4/4 [==============================] - 1s 4ms/step - loss: 1.3201 - accuracy: 0.2083
Epoch 2/300
4/4 [==============================] - 0s 5ms/step - loss: 1.1310 - accuracy: 0.3333
Epoch 3/300
4/4 [==============================] - 0s 5ms/step - loss: 0.9205 - accuracy: 0.5750
Epoch 4/300
4/4 [==============================] - 0s 4ms/step - loss: 0.7546 - accuracy: 0.7167
Epoch 5/300
4/4 [==============================] - 0s 4ms/step - loss: 0.6357 - accuracy: 0.7917
Epoch 6/300
4/4 [==============================] - 0s 6ms/step - loss: 0.5489 - accuracy: 0.8000
Epoch 7/300
4/4 [==============================] - 0s 4ms/step - loss: 0.4882 - accuracy: 0.8333
Epoch 8/300
4/4 [==============================] - 0s 5ms/step - loss: 0.4409 - accuracy: 0.8500
Epoch 9/300
4/4 [==============================] - 0s 4ms/step - loss: 0.4050 - accuracy: 0.8583
Epoch 10/300
4/4 [==============================] - 0s 4ms/step - loss: 0.3775 - accuracy: 0.8583
Epoch 11/300
4/4 [===========

In [24]:
score = model.evaluate(X_test, y_test, verbose = 0)

In [26]:
print('Test score:', score[0])
print('Test accuracy:', score[1])

Test score: 0.030197778716683388
Test accuracy: 1.0


In [27]:
y_pred = model.predict(X_test)

In [28]:
y_test_class = np.argmax(y_test, axis=1)
y_pred_class = np.argmax(y_pred, axis=1)

print(classification_report(y_test_class, y_pred_class))
print(confusion_matrix(y_test_class, y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
